unit U_itinerario;

interface
{$warnings off}
{$hints off}
uses windows;

Var
  _CARACTERES_VALIDOS_OCUPANTES : SET OF CHAR = ['0','1','2','3','4','5','6','7','8','9', #08];
  _CARACTERES_VALIDOS_TERMINALES : SET OF CHAR = ['0','1','2','3','4','5','6','7','8','9', #08, ':', 'S','N','s','n'];


Const
 _SER_SERVICIO_ALL  = 'SELECT TIPOSERVICIO, ABREVIACION FROM SERVICIOS WHERE TIPOSERVICIO > 0 AND FECHA_BAJA IS NULL ORDER BY 1;';
 _ITI_SELECT_RUTA   = 'SELECT ID_RUTA,  CONCAT(ORIGEN , ''-'' , DESTINO, '' - '', ID_RUTA ) FROM T_C_RUTA ORDER BY 2';
 _QUERY_TERMINALES = 'SELECT ID_TERMINAL, DESCRIPCION FROM T_C_TERMINAL WHERE FECHA_BAJA IS NULL ORDER BY DESCRIPCION;';
 _QUERY_IVAS = 'SELECT VALOR,VALOR FROM PDV_C_IVA WHERE BAJA IS NULL';
 _QUERY_VACIO_CB = 'SELECT VALOR FROM PDV_C_PARAMETRO WHERE ID_PARAMETRO = 28';

 _SER_SERVICIO_EMPRESA = 'SELECT DISTINCT(S.TIPOSERVICIO), S.ABREVIACION '+
                         'FROM PDV_C_GRUPO_SERVICIOS G INNER JOIN SERVICIOS S ON S.ID_GRUPO = G.ID_GRUPO '+
                         'WHERE G.ID_GRUPO IN ( '+
                         'SELECT ID_GRUPO FROM PDV_C_GRUPO_SERVICIOS 	WHERE ID_TERMINAL = ''%s'') AND S.TIPOSERVICIO > 0 AND  FECHA_BAJA IS NULL ORDER BY 1';

 _COL_TERMINAL = 0;
 _COL_HORA = 1;
 _COL_CUPO = 2;
 _COL_PIE = 3;
 _COL_CHKC = 4;
 _ERROR = MB_ICONERROR;
 _ATENCION = MB_ICONWARNING;
 _OK = MB_ICONASTERISK;

 _NUEVA = 'Nueva-0';


implementation

end.
