DROP PROCEDURE IF EXISTS ASIENTO_RESERVADO_PASAJERO;
DELIMITER $$
CREATE PROCEDURE ASIENTO_RESERVADO_PASAJERO(IN IN_FECHA_INPUT VARCHAR(20), IN IN_CORRIDA INTEGER,
                                            IN IN_PASAJERO VARCHAR(40))
BEGIN
    SELECT A.NO_ASIENTO,
            CASE A.STATUS
                WHEN 'R' THEN 'R'
            END AS TEXTO
    FROM PDV_T_ASIENTO A INNER JOIN PDV_T_CORRIDA C ON
                      (C.ID_CORRIDA = A.ID_CORRIDA AND C.FECHA = CAST(A.FECHA_HORA_CORRIDA AS DATE))
    WHERE A.FECHA_HORA_CORRIDA = CAST(IN_FECHA_INPUT AS DATETIME) AND A.ID_CORRIDA = IN_CORRIDA AND
          NOMBRE_PASAJERO = IN_PASAJERO;
END$$
DELIMITER;