DROP PROCEDURE IF EXISTS AUTOLIBERABLE;
DELIMITER$$
CREATE PROCEDURE AUTOLIBERABLE(IN PASAJERO VARCHAR(40), IN IN_CORRIDA INTEGER,
                               IN FECHA VARCHAR(19), IN IN_ASIENTO INTEGER)
BEGIN
    UPDATE PDV_T_ASIENTO SET NOMBRE_PASAJERO = PASAJERO
    WHERE ID_CORRIDA = IN_CORRIDA AND FECHA_HORA_CORRIDA = CAST(FECHA AS DATETIME) AND NO_ASIENTO = IN_ASIENTO;
END$$
DELIMITER;