DROP PROCEDURE IF EXISTS DESCUENTO_OCUPANTE;
DELIMITER $$
CREATE PROCEDURE DESCUENTO_OCUPANTE(IN IN_ABREVIA VARCHAR(1))
BEGIN
    SELECT O.ID_OCUPANTE,O.DESCRIPCION, O.DESCUENTO FROM PDV_C_OCUPANTE O
    WHERE O.ABREVIACION = IN_ABREVIA;
END$$
DELIMITER;