DELIMITER $$

DROP PROCEDURE IF EXISTS `corporativo`.`GETCOORDENADAS`$$
CREATE DEFINER=`venta`@`%` PROCEDURE  `corporativo`.`GETCOORDENADAS`(IN BUS INTEGER)
BEGIN
    SELECT ASIENTO, X, Y
    FROM PDV_C_TIPO_AUTOBUS_D
    WHERE ID_TIPO_AUTOBUS = BUS
    ORDER BY ASIENTO ;

END $$

DELIMITER ;