DROP PROCEDURE IF EXISTS SHOW_DETALLE_RUTA;
DELIMITER $$
CREATE PROCEDURE SHOW_DETALLE_RUTA(IN IN_RUTA INTEGER)
BEGIN
    SELECT DISTINCT(D.ORDEN), T.DESTINO, TE.DESCRIPCION
    FROM T_C_RUTA R INNER JOIN T_C_RUTA_D D ON R.ID_RUTA = D.ID_RUTA
                    INNER JOIN T_C_TRAMO T ON T.ID_TRAMO = D.ID_TRAMO
                    INNER JOIN T_C_TERMINAL TE ON TE.ID_TERMINAL = T.DESTINO
    WHERE R.ID_RUTA = IN_RUTA
    ORDER BY D.ORDEN;
END$$
DELIMITER ;