DROP PROCEDURE IF EXISTS SHOW_OCUPANTES;
DELIMITER$$
CREATE PROCEDURE SHOW_OCUPANTES(IN IN_TERMINAL VARCHAR(5), IN IN_FECHA DATE, IN IN_CORRIDA INTEGER)
BEGIN
    SELECT O.DESCRIPCION,
      ((SELECT IO.MAXIMO
       FROM PDV_C_ITINERARIO_D D INNER JOIN PDV_C_ITINERARIO_OCUPANTE IO ON
                                      (D.ID_TERMINAL = IO.ID_TERMINAL AND D.ID_CORRIDA = IO.ID_CORRIDA)
                                 INNER JOIN PDV_C_OCUPANTE  O ON O.ID_OCUPANTE = IO.ID_CORRIDA
       WHERE D.ID_TERMINAL = IN_TERMINAL AND D.ID_CORRIDA  = IN_CORRIDA) - COUNT(B.ID_OCUPANTE)) AS RESTANTE
    FROM PDV_T_BOLETO B INNER JOIN PDV_C_OCUPANTE O ON B.ID_OCUPANTE = O.ID_OCUPANTE
    WHERE ID_CORRIDA = IN_CORRIDA AND CAST(FECHA_CORRIDA AS DATE) = IN_FECHA AND B.ID_TERMINAL = IN_TERMINAL
    GROUP BY B.ID_OCUPANTE;
END$$
DELIMITER $$