DROP PROCEDURE IF EXISTS PDV_STORE_ASIENTOS_DISPONIBLES_CUALES;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_ASIENTOS_DISPONIBLES_CUALES(IN IN_CORRIDA VARCHAR(10), IN FECHA_INPUT DATE, IN ASIENTO VARCHAR(40))
BEGIN
    SELECT A.NO_ASIENTO,
            CASE A.STATUS
                WHEN 'V' THEN CONCAT(A.ORIGEN, ' ' ,A.DESTINO)
                WHEN 'R' THEN 'R'
                WHEN 'A' THEN 'A'
            END AS TEXTO
    FROM PDV_T_ASIENTO A INNER JOIN PDV_T_CORRIDA C ON
                      (C.ID_CORRIDA = A.ID_CORRIDA AND C.FECHA = CAST(A.FECHA_HORA_CORRIDA AS DATE))
    WHERE C.FECHA = FECHA_INPUT AND A.ID_CORRIDA = IN_CORRIDA AND NO_ASIENTO IN (ASIENTO);
END $$

DELIMITER ;