DROP PROCEDURE IF EXISTS PDV_STORE_ASIENTOS_DISPONIBLES;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_ASIENTOS_DISPONIBLES(IN IN_CORRIDA VARCHAR(10), IN FECHA_INPUT VARCHAR(25), IN_PIE INTEGER)
BEGIN
    IF IN_PIE = 0 THEN
        SELECT A.NO_ASIENTO,
                CASE A.STATUS
                    WHEN 'V' THEN CONCAT(A.ORIGEN, ' ' ,A.DESTINO)
                    WHEN 'R' THEN 'R'
                    WHEN 'A' THEN 'A'
                END AS TEXTO, A.STATUS
        FROM PDV_T_ASIENTO A INNER JOIN PDV_T_CORRIDA C ON
                          (C.ID_CORRIDA = A.ID_CORRIDA AND C.FECHA = CAST(A.FECHA_HORA_CORRIDA AS DATE))
        WHERE A.FECHA_HORA_CORRIDA = FECHA_INPUT AND A.ID_CORRIDA = IN_CORRIDA AND
              A.NO_ASIENTO < 100;
    END IF;

    IF IN_PIE = 1 THEN
        SELECT A.NO_ASIENTO,
                CASE A.STATUS
                    WHEN 'V' THEN CONCAT(A.ORIGEN, ' ' ,A.DESTINO)
                    WHEN 'R' THEN 'R'
                    WHEN 'A' THEN 'A'
                END AS TEXTO, A.STATUS
        FROM PDV_T_ASIENTO A INNER JOIN PDV_T_CORRIDA C ON
                          (C.ID_CORRIDA = A.ID_CORRIDA AND C.FECHA = CAST(A.FECHA_HORA_CORRIDA AS DATE))
        WHERE A.FECHA_HORA_CORRIDA = FECHA_INPUT AND A.ID_CORRIDA = IN_CORRIDA AND
              A.NO_ASIENTO > 100;
    END IF;

END $$

DELIMITER ;