DROP PROCEDURE IF EXISTS PDV_STORE_BORRA_BUS_CORDENADA;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_BORRA_BUS_CORDENADA(IN BUS_ID INTEGER)
BEGIN
    DELETE FROM PDV_C_TIPO_AUTOBUS_D WHERE ID_TIPO_AUTOBUS = BUS_ID;
END $$

DELIMITER ;