DROP PROCEDURE IF EXISTS PDV_STORE_CORRIDAS;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_CORRIDAS(IN IN_ORIGEN VARCHAR(5), IN IN_DESTINO VARCHAR(5),
                                                     IN FECHA_INPUT DATE, IN FECHA_SIGUIENTE DATE)
BEGIN

END$$
DELIMITER;