DROP PROCEDURE IF EXISTS PDV_STORE_ASIENTOS_CANCELA;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_ASIENTOS_CANCELA(IN IN_CORRIDA VARCHAR(10), IN IN_FECHA DATE, IN IN_TIME TIME)
BEGIN
    SELECT  NO_ASIENTO
    FROM PDV_T_ASIENTO
    WHERE ID_CORRIDA = IN_CORRIDA AND CAST(FECHA_HORA_CORRIDA AS DATE) = IN_FECHA AND
          CAST(FECHA_HORA_CORRIDA AS TIME) = IN_TIME
    ORDER BY NO_ASIENTO;
END$$
DELIMITER;