DELIMITER $$

DROP PROCEDURE IF EXISTS `PDV_STORE_SHOW_OCUPANTES` $$
CREATE DEFINER=`venta`@`%` PROCEDURE `PDV_STORE_SHOW_OCUPANTES`(IN IN_TERMINAL VARCHAR(5), IN IN_FECHA DATE, IN IN_CORRIDA VARCHAR(10))
BEGIN
    DECLARE DIA_INICIO, DIA_FINAL DATE;
    DECLARE CONTADOR  INT;
    SELECT (COUNT(ID_PERIODO_VACACIONAL))AS TOTAL INTO CONTADOR FROM PDV_C_PERIODO_VACACIONAL WHERE FECHA_INICIO <= IN_FECHA AND FECHA_FIN >= IN_FECHA;

    SELECT FECHA_INICIO, FECHA_FIN INTO DIA_INICIO, DIA_FINAL FROM PDV_C_PERIODO_VACACIONAL;
--      IF ((IN_FECHA >= DIA_INICIO) AND (DIA_FINAL >= IN_FECHA)) THEN
--    IF ((DIA_INICIO <= IN_FECHA) AND (DIA_FINAL >= IN_FECHA)) THEN
      IF (CONTADOR = 1) THEN
          SELECT O.DESCRIPCION, (CO.MAXIMO -
                                  (SELECT COUNT(B.ID_OCUPANTE)
                                   FROM PDV_T_ASIENTO A INNER JOIN PDV_T_BOLETO B ON B.NO_ASIENTO = A.NO_ASIENTO AND
                                                                     B.FECHA = CAST(A.FECHA_HORA_CORRIDA AS DATE) AND
                                                                     B.ID_CORRIDA = A.ID_CORRIDA
                                   WHERE CAST(A.FECHA_HORA_CORRIDA AS DATE) = CO.FECHA AND
                                           A.ID_CORRIDA = CO.ID_CORRIDA AND A.STATUS = 'V' AND B.ID_OCUPANTE = O.ID_OCUPANTE))AS TOTAL


          FROM PDV_C_OCUPANTE O LEFT JOIN PDV_T_CORRIDA_OCUPANTE CO ON O.ID_OCUPANTE = CO.ID_OCUPANTE
          WHERE CO.ID_CORRIDA = IN_CORRIDA AND CO.FECHA = IN_FECHA  AND CO.ID_TERMINAL = IN_TERMINAL
        UNION
          SELECT 'PIE',(PIE - (SELECT COALESCE(COUNT(NO_ASIENTO),0)
                    FROM PDV_T_ASIENTO
                    WHERE NO_ASIENTO > 100 AND ID_CORRIDA = IN_CORRIDA AND STATUS = 'V' AND CAST(FECHA_HORA_CORRIDA AS DATE) = IN_FECHA ))
          FROM PDV_T_CORRIDA_D
          WHERE ID_CORRIDA = IN_CORRIDA  AND FECHA = IN_FECHA AND ID_TERMINAL = IN_TERMINAL
          ORDER BY 1;
    END IF;

    IF (CONTADOR = 0) THEN
          SELECT DESCRIPCION , (0) AS TOTAL
          FROM PDV_C_OCUPANTE O
          WHERE ID_OCUPANTE  IN (2,3)
          UNION
          SELECT DESCRIPCION,
              (COALESCE((SELECT CO.MAXIMO FROM PDV_T_CORRIDA_OCUPANTE CO
                         WHERE CO.ID_OCUPANTE = 4 AND CO.ID_CORRIDA = IN_CORRIDA AND FECHA = IN_FECHA AND
                               CO.ID_TERMINAL = IN_TERMINAL),0) -
                        (SELECT COUNT(*) FROM PDV_T_BOLETO B
                        WHERE B.FECHA = IN_FECHA AND B.ID_OCUPANTE = O.ID_OCUPANTE AND
                        ESTATUS = 'V' AND ORIGEN = IN_TERMINAL AND ID_CORRIDA = IN_CORRIDA))
          FROM PDV_C_OCUPANTE O
          WHERE O.ID_OCUPANTE = 4
          UNION
          SELECT 'PIE',(PIE - (SELECT COALESCE(COUNT(NO_ASIENTO),0)
          FROM PDV_T_ASIENTO
          WHERE NO_ASIENTO > 100 AND ID_CORRIDA = IN_CORRIDA AND STATUS = 'V' AND CAST(FECHA_HORA_CORRIDA AS DATE) = IN_FECHA ))
          FROM PDV_T_CORRIDA_D
          WHERE ID_CORRIDA = IN_CORRIDA AND  FECHA = IN_FECHA AND ID_TERMINAL = IN_TERMINAL
          UNION
          SELECT DESCRIPCION,
              (COALESCE((SELECT CO.MAXIMO FROM PDV_T_CORRIDA_OCUPANTE CO
                       WHERE CO.ID_OCUPANTE NOT IN (2,3,4) AND CO.ID_CORRIDA = IN_CORRIDA AND
                             CO.FECHA = IN_FECHA AND CO.ID_TERMINAL = IN_TERMINAL AND O.ID_OCUPANTE = CO.ID_OCUPANTE),0)) -
              ((SELECT COUNT(*) FROM PDV_T_BOLETO B
                        WHERE B.FECHA = IN_FECHA AND B.ID_OCUPANTE = O.ID_OCUPANTE AND
                        ESTATUS = 'V' AND ORIGEN = IN_TERMINAL AND ID_CORRIDA = IN_CORRIDA))
          FROM PDV_C_OCUPANTE O
          WHERE O.ID_OCUPANTE NOT IN (2,3,4);
    END IF;
END $$

DELIMITER ;