DROP PROCEDURE IF EXISTS PDV_STORE_ASIENTOS_RESERVADOS;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_ASIENTOS_RESERVADOS(IN IN_CORRIDA VARCHAR(10), IN FECHA_INPUT VARCHAR(10), IN PASAJERO VARCHAR(40))
BEGIN
    SELECT NO_ASIENTO,
            CASE A.STATUS
                WHEN 'V' THEN CONCAT(A.ORIGEN, ' ' ,A.DESTINO)
                WHEN 'R' THEN 'R'
                WHEN 'A' THEN 'A'
            END AS TEXTO
    FROM PDV_T_ASIENTO A INNER JOIN PDV_T_CORRIDA C ON
                      (C.ID_CORRIDA = A.ID_CORRIDA AND C.FECHA = CAST(A.FECHA_HORA_CORRIDA AS DATE))
    WHERE A.ID_CORRIDA = IN_CORRIDA AND CAST(A.FECHA_HORA_CORRIDA AS DATE) = FECHA_INPUT AND
           A.NOMBRE_PASAJERO = PASAJERO
    UNION
    SELECT NO_ASIENTO,
            CASE A.STATUS
                WHEN 'V' THEN CONCAT(A.ORIGEN, ' ' ,A.DESTINO)
                WHEN 'R' THEN 'R'
                WHEN 'A' THEN 'A'
            END AS TEXTO
    FROM PDV_T_ASIENTO A INNER JOIN PDV_T_CORRIDA C ON
                      (C.ID_CORRIDA = A.ID_CORRIDA AND C.FECHA = CAST(A.FECHA_HORA_CORRIDA AS DATE))
    WHERE A.ID_CORRIDA = IN_CORRIDA AND CAST(A.FECHA_HORA_CORRIDA AS DATE) = FECHA_INPUT
    ORDER BY 1;
END $$

DELIMITER ;