DROP PROCEDURE IF EXISTS PDV_STORE_SHOW_OCUPANTES_PERIODO;
DELIMITER $$
/*  Para este store los ocupantes por default que aplican para la
    venta son las claves 1 y 4 estos siempre estan disponibles para la venta
*/
CREATE PROCEDURE PDV_STORE_SHOW_OCUPANTES_PERIODO(IN IN_TERMINAL VARCHAR(5), IN IN_FECHA DATE, IN IN_CORRIDA VARCHAR(10))
BEGIN
    DECLARE DIA_INICIO, DIA_FINAL DATE;

    SELECT FECHA_INICIO, FECHA_FIN INTO DIA_INICIO, DIA_FINAL FROM PDV_C_PERIODO_VACACIONAL;

    IF ((DIA_INICIO <= IN_FECHA) AND (DIA_FINAL >= IN_FECHA)) THEN
          SELECT O.DESCRIPCION, (CO.MAXIMO-
                                  (SELECT COUNT(B.ID_OCUPANTE)
                                   FROM PDV_T_BOLETO B INNER JOIN PDV_T_CORRIDA C ON B.ID_CORRIDA = C.ID_CORRIDA AND B.FECHA = C.FECHA
                                   WHERE B.ID_CORRIDA = CO.ID_CORRIDA AND  B.FECHA = CO.FECHA AND O.ABREVIACION = B.TIPO_TARIFA))AS TOTAL
          FROM PDV_C_OCUPANTE O LEFT JOIN PDV_T_CORRIDA_OCUPANTE CO ON O.ID_OCUPANTE = CO.ID_OCUPANTE
          WHERE CO.ID_CORRIDA = IN_CORRIDA AND CO.FECHA = IN_FECHA  AND CO.ID_TERMINAL = IN_TERMINAL
        UNION
          SELECT 'PIE',(PIE - (SELECT COALESCE(COUNT(NO_ASIENTO),0)
                    FROM PDV_T_ASIENTO
                    WHERE NO_ASIENTO > 100 AND ID_CORRIDA = IN_CORRIDA AND STATUS = 'V' AND CAST(FECHA_HORA_CORRIDA AS DATE) = IN_FECHA ))
          FROM PDV_T_CORRIDA_D
          WHERE ID_CORRIDA = IN_CORRIDA  AND FECHA = IN_FECHA AND ID_TERMINAL = IN_TERMINAL;
    ELSE
          SELECT DESCRIPCION , (0) AS TOTAL
          FROM PDV_C_OCUPANTE O
          WHERE ID_OCUPANTE > 1 AND ID_OCUPANTE <> 4
        UNION
          SELECT DESCRIPCION,
          (COALESCE((SELECT CO.MAXIMO FROM PDV_T_CORRIDA_OCUPANTE CO
           WHERE CO.ID_OCUPANTE = 4 AND CO.ID_CORRIDA = IN_CORRIDA AND FECHA = IN_FECHA AND CO.ID_TERMINAL = IN_TERMINAL),0) -
           (SELECT COUNT(*) FROM PDV_T_BOLETO B
            WHERE B.FECHA = IN_FECHA AND B.ID_OCUPANTE = O.ID_OCUPANTE AND
                  ESTATUS = 'V' AND ORIGEN = IN_TERMINAL AND ID_CORRIDA = IN_CORRIDA))
          FROM PDV_C_OCUPANTE O
          WHERE O.ID_OCUPANTE = 4


        UNION
          SELECT 'PIE',(PIE - (SELECT COALESCE(COUNT(NO_ASIENTO),0)
          FROM PDV_T_ASIENTO
          WHERE NO_ASIENTO > 100 AND ID_CORRIDA = IN_CORRIDA AND STATUS = 'V' AND CAST(FECHA_HORA_CORRIDA AS DATE) = IN_FECHA ))
          FROM PDV_T_CORRIDA_D
          WHERE ID_CORRIDA = IN_CORRIDA AND  FECHA = IN_FECHA AND ID_TERMINAL = IN_TERMINAL;

    END IF;
END $$

DELIMITER ;