DROP PROCEDURE IF EXISTS PDV_STORE_BUSCA_POR_AUTOBUS_XY;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_BUSCA_POR_AUTOBUS_XY(IN IN_ID_BUS INTEGER)
BEGIN
    SELECT ASIENTO, X, Y
    FROM PDV_C_TIPO_AUTOBUS_D
    WHERE ID_TIPO_AUTOBUS = IN_ID_BUS;
END $$

DELIMITER ;