DROP PROCEDURE IF EXISTS PDV_STORE_ADD_COORDENADAS;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_ADD_COORDENADAS(IN ID_BUS INTEGER, IN X INTEGER, IN Y INTEGER, IN NUMERO  INTEGER)
BEGIN
    INSERT INTO PDV_C_TIPO_AUTOBUS_D(ID_TIPO_AUTOBUS, ASIENTO, X, Y)
    VALUES(ID_BUS, NUMERO, X, Y);
END $$

DELIMITER ;