DROP PROCEDURE IF EXISTS PDV_STORE_TARIFA;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_TARIFA(IN IN_ORIGEN VARCHAR(9), IN IN_DESTINO VARCHAR(9), IN IN_ABREVIA VARCHAR(20))
BEGIN
    SELECT MONTO
    FROM PDV_C_TARIFA T INNER JOIN SERVICIOS S ON T.ID_SERVICIO = S.TIPOSERVICIO
                       INNER JOIN PDV_C_TARIFA_D D ON D.ID_TARIFA = T.ID_TARIFA
    WHERE T.ID_TRAMO = (SELECT T.ID_TRAMO FROM T_C_TRAMO T WHERE T.ORIGEN = IN_ORIGEN AND T.DESTINO = IN_DESTINO)
           AND S.ABREVIACION = IN_ABREVIA AND FECHA_HORA_APLICA <= NOW()
    ORDER BY FECHA_HORA_APLICA DESC
    LIMIT 1;
END $$
DELIMITER ;