DROP PROCEDURE IF EXISTS PDV_STORE_CORRIDA_ACTUALIZADA;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_CORRIDA_ACTUALIZADA(IN CORRIDA VARCHAR(10), IN EMPLEADO VARCHAR(7),
                                IN INPUT_FECHA DATE, IN INPUT_HORA TIME, IN TERMINAL VARCHAR(5))
BEGIN
      UPDATE PDV_T_CORRIDA_D SET TRAB_ID = EMPLEADO
      WHERE ID_CORRIDA = CORRIDA AND FECHA = INPUT_FECHA AND ID_TERMINAL = TERMINAL AND
            HORA = INPUT_HORA;
END $$

DELIMITER ;