DROP PROCEDURE IF EXISTS PDV_STORE_SHOW_DETALLE_RUTA;
DELIMITER $$
CREATE PROCEDURE PDV_STORE_SHOW_DETALLE_RUTA(IN IN_RUTA INTEGER)
BEGIN
    DECLARE TARIFA  INT;
    SELECT VALOR INTO TARIFA  FROM PDV_C_PARAMETRO WHERE ID_PARAMETRO = 10;
-- MUESTRA LAS TARIFAS DE LOS TRAMOS

      SELECT DISTINCT(D.ORDEN), T.DESTINO, TE.DESCRIPCION
      FROM T_C_RUTA R INNER JOIN T_C_RUTA_D D ON R.ID_RUTA = D.ID_RUTA
                    INNER JOIN T_C_TRAMO T ON T.ID_TRAMO = D.ID_TRAMO
                    INNER JOIN PDV_C_TARIFA FA ON FA.ID_TRAMO = T.ID_TRAMO
                    INNER JOIN PDV_C_TARIFA_D FD ON FD.ID_TARIFA = FA.ID_TARIFA
                    INNER JOIN T_C_TERMINAL TE ON TE.ID_TERMINAL = T.DESTINO
      WHERE R.ID_RUTA = IN_RUTA 
      ORDER BY D.ORDEN;


END $$

DELIMITER ;