DROP PROCEDURE IF EXISTS REGISTRA_BOLETO;
DELIMITER $$
CREATE PROCEDURE REGISTRA_BOLETO(IN IN_BOLETO INTEGER, IN IN_TERMINAL VARCHAR(5), IN IN_TRABID VARCHAR(7),
                                 IN IN_ESTATUS VARCHAR(1),IN IN_ORIGEN VARCHAR(5), IN IN_DESTINO VARCHAR(5),
                                 IN IN_TARIFA DOUBLE, IN IN_FORMA_PAGO INTEGER, IN IN_TAQUILLA INTEGER,
                                 IN IN_TIPO_TARIFA VARCHAR(1), IN IN_CORRIDA INTEGER, IN IN_FECHA DATE,
                                 IN IN_PASAJERO VARCHAR(40), IN IN_ASIENTO INTEGER, IN IN_OCUPANTE INTEGER)
BEGIN
    DECLARE ACTUAL DATETIME;
    SET ACTUAL = NOW();
    INSERT INTO PDV_T_BOLETO(ID_BOLETO, ID_TERMINAL, TRAB_ID, ESTATUS,
                             ORIGEN, DESTINO, TARIFA, ID_FORMA_PAGO,
                             ID_TAQUILLA, TIPO_TARIFA, FECHA_HORA_BOLETO, ID_CORRIDA,
                             FECHA, NOMBRE_PASAJERO, NO_ASIENTO, ID_OCUPANTE)
    VALUES(IN_BOLETO, IN_TERMINAL, IN_TRABID, IN_ESTATUS,
           IN_ORIGEN, IN_DESTINO, IN_TARIFA, IN_FORMA_PAGO,
           IN_TAQUILLA, IN_TIPO_TARIFA, CAST(ACTUAL AS DATETIME), IN_CORRIDA,
           IN_FECHA, IN_PASAJERO, IN_ASIENTO, IN_OCUPANTE);
END$$
DELIMITER;