DELIMITER $$

DROP PROCEDURE IF EXISTS `SHOW_OCUPANTES` $$
CREATE DEFINER=`venta`@`%` PROCEDURE `SHOW_OCUPANTES`(IN IN_TERMINAL VARCHAR(5), IN IN_FECHA DATE, IN IN_CORRIDA INTEGER,
                                                      IN IN_SERVICIO INTEGER, IN IN_BUS INTEGER, IN IN_RUTA INTEGER)
BEGIN
--  SELECT O.DESCRIPCION,
--   (
-- COALESCE(
--   (SELECT IO.MAXIMO
--     FROM PDV_C_ITINERARIO_D D INNER JOIN PDV_C_ITINERARIO_OCUPANTE IO ON (D.ID_TERMINAL = IO.ID_TERMINAL AND D.ID_CORRIDA = IO.ID_CORRIDA)
--                               INNER JOIN PDV_C_OCUPANTE  O ON O.ID_OCUPANTE = IO.ID_CORRIDA
--     WHERE D.ID_TERMINAL = IN_TERMINAL AND D.ID_CORRIDA  = IN_CORRIDA) - COUNT(B.ID_OCUPANTE),0)   ) AS TOTAL
--  FROM PDV_T_BOLETO B INNER JOIN PDV_C_OCUPANTE O ON B.ID_OCUPANTE = O.ID_OCUPANTE
--  WHERE ID_CORRIDA = IN_CORRIDA AND CAST(FECHA_HORA_BOLETO AS DATE) = IN_FECHA AND B.ID_TERMINAL = IN_TERMINAL
--  GROUP BY B.ID_OCUPANTE;

SELECT O.DESCRIPCION, (IO.MAXIMO - COALESCE(
                (SELECT COUNT(B.ID_OCUPANTE)
                FROM PDV_T_BOLETO B INNER JOIN PDV_T_CORRIDA C ON B.ID_CORRIDA = C.ID_CORRIDA AND
                                                                  B.FECHA = C.FECHA
                WHERE B.ID_CORRIDA = I.ID_CORRIDA AND B.ID_TERMINAL = D.ID_TERMINAL AND B.FECHA = IN_FECHA AND
                      O.ABREVIACION = B.TIPO_TARIFA
                GROUP BY B.ID_OCUPANTE),0)) AS TOTAL
FROM PDV_C_ITINERARIO I INNER JOIN PDV_C_ITINERARIO_D D ON I.ID_CORRIDA = D.ID_CORRIDA
                        INNER JOIN PDV_C_ITINERARIO_OCUPANTE IO ON IO.ID_TERMINAL = D.ID_TERMINAL AND
                                                                   IO.ID_CORRIDA  = D.ID_CORRIDA
                        INNER JOIN PDV_C_OCUPANTE O ON O.ID_OCUPANTE = IO.ID_OCUPANTE
WHERE I.ID_CORRIDA = IN_CORRIDA AND I.TIPOSERVICIO = IN_SERVICIO AND ID_TIPO_AUTOBUS = IN_BUS AND I.ID_RUTA = IN_RUTA AND
      D.ID_TERMINAL = IN_TERMINAL;



END $$

DELIMITER ;