DROP PROCEDURE IF EXISTS TARIFA_TRAMO;
DELIMITER $$
CREATE PROCEDURE TARIFA_TRAMO(IN ID_TRAMO INTEGER, IN IN_SERVICIO VARCHAR(18))
BEGIN
    SELECT MONTO, MAX(FECHA_HORA_APLICA)
    FROM PDV_C_TARIFA T INNER JOIN SERVICIOS S ON T.ID_SERVICIO = S.TIPOSERVICIO
                        INNER JOIN PDV_C_TARIFA_D D ON D.ID_TARIFA = T.ID_TARIFA
    WHERE T.ID_TRAMO = ID_TRAMO AND S.ABREVIACION = IN_SERVICIO AND FECHA_HORA_APLICA < NOW();
END $$
DELIMITER ;