DELIMITER $$

DROP PROCEDURE IF EXISTS PDV_RECOLECTA $$
CREATE PROCEDURE PDV_RECOLECTA(IN  _TERMINAL VARCHAR(10), IN _TAQUILLA INT, IN _EMPLEADO VARCHAR(10),
                                                     IN  _EMPLEADO_REALIZA VARCHAR(10), IN _IMPORTE REAL,
                                                     OUT _ESTATUS INTEGER)
BEGIN
DECLARE _ID_CORTE INT;
DECLARE _TOTAL_CORTES INT;
DECLARE FECHA1, FECHA2 DATETIME;
DECLARE _TOTAL_EFECTIVO REAL;

DECLARE ASIGNA_FECHAS CURSOR FOR SELECT FECHA_INICIO, NOW()
                                 FROM  PDV_T_CORTE
                                 WHERE ID_CORTE = _ID_CORTE AND ID_TERMINAL= _TERMINAL;
-- CURSOR PARA TOMAR LA FECHA INICIAL Y LA FECHA ACTUAL PARA SABER QUE PERIODO SUMAR LO QUE HA VENDIDO UN PROMOTOR
DECLARE CUENTA_CORTES CURSOR FOR SELECT COUNT(*) AS TOTAL
                               FROM  PDV_T_CORTE
                               WHERE ID_TERMINAL= _TERMINAL AND ID_EMPLEADO= _EMPLEADO
                               AND ESTATUS <> 'F' AND FECHA_FIN IS NULL;
-- CURSOR PARA CONTAR CUANTOS CORTES EXISTEN DE UN DETERMINADO EMPLEADO EN LA TERMINAL TRABAJADA
DECLARE BUSCA_FOLIO CURSOR FOR SELECT ID_CORTE
                               FROM  PDV_T_CORTE
                               WHERE ID_TERMINAL= _TERMINAL AND ID_EMPLEADO= _EMPLEADO
                               AND ESTATUS <> 'F' AND FECHA_FIN IS NULL;
-- CURSOR PARA ASIGNAR EL NUMERO DE CORTE DE UN EMPLEADO, CON LOS ELEMENTOS ACTUALMENTE EN LA BASE DE DATOS
DECLARE TOTAL_EFECTIVO CURSOR FOR SELECT (SELECT COALESCE(SUM(TARIFA),0) AS EFECTIVO
                                  FROM PDV_T_BOLETO
                                  WHERE FECHA_HORA_BOLETO BETWEEN FECHA1 AND FECHA2 AND TRAB_ID = _EMPLEADO AND ESTATUS='V') -
                                  (
                                    SELECT COALESCE(SUM(IMPORTE),0) AS EFECTIVO
                                    FROM PDV_T_RECOLECCION
                                    WHERE FECHA_HORA BETWEEN FECHA1 AND FECHA2 AND ID_EMPLEADO = _EMPLEADO AND ID_CORTE = _ID_CORTE
                                    AND ID_TERMINAL= _TERMINAL
                                  ) AS EFECTIVO;
-- CURSOR PARA SABER CUANTO LLEVA VENDIDO EL PROMOTOR  SIN LAS RECOLECCIONES REALIZADAS
SET _ESTATUS=1;

OPEN BUSCA_FOLIO;
FETCH BUSCA_FOLIO INTO _ID_CORTE;

OPEN CUENTA_CORTES;
FETCH CUENTA_CORTES  INTO _TOTAL_CORTES;

IF _TOTAL_CORTES > 1 THEN
    SET _ESTATUS = 2; -- EL ESTATUS ES 2 CUANDO LOS CORTES EXISTENTES PARA UN EMPLEADO EN LA MISMA TERMINAL ES MAYOR A 1
    select 'EL ESTATUS ES 2 CUANDO LOS CORTES EXISTENTES PARA UN EMPLEADO EN LA MISMA TERMINAL ES MAYOR A 1';
   -- EXIT;
END IF;

OPEN ASIGNA_FECHAS; -- ABRO EL CURSOR
FETCH ASIGNA_FECHAS INTO FECHA1, FECHA2; -- ASIGNO VALORES

OPEN  TOTAL_EFECTIVO ;
FETCH TOTAL_EFECTIVO INTO   _TOTAL_EFECTIVO;

IF _TOTAL_EFECTIVO < _IMPORTE THEN
    SET _ESTATUS = 3; -- EL ESTATUS 3 ES CUANDO EL TOTAL DE LO QUE EL EMPLEADO HA VENDIDO NO ALCANZA PARA HACER LA RECOLECCION
                     -- TOMANDO EN CUENTA VENTA_TOTAL - RECOLECCIONES = EFECTIVO EN TAQUILLA
    select 'EL ESTATUS 3 ES CUANDO EL TOTAL DE LO QUE EL EMPLEADO HA VENDIDO NO ALCANZA PARA HACER LA RECOLECCION';
END IF;

IF _ESTATUS = 1 THEN
    INSERT INTO PDV_T_RECOLECCION(ID_TERMINAL, ID_TAQUILLA, ID_CORTE,   FECHA_HORA, ID_EMPLEADO, ID_EMPLEADO_REALIZA, IMPORTE)
    VALUES(                       _TERMINAL,   _TAQUILLA,    _ID_CORTE, NOW(),      _EMPLEADO,  _EMPLEADO_REALIZA, _IMPORTE);
END IF;



-- CIERRO LOS CURSORES
CLOSE ASIGNA_FECHAS;
CLOSE CUENTA_CORTES;
CLOSE TOTAL_EFECTIVO;
CLOSE BUSCA_FOLIO;



END $$

DELIMITER ;