USE information_schema;



-- SELECT * FROM `COLUMNS` C WHERE C.TABLE_NAME = 'PDV_T_GUIA' AND C.COLUMN_NAME IN ('HORA_CORRIDA', 'TIPO_CORRIDA') ;

-- SELECT COUNT(*) FROM `COLUMNS` C WHERE C.TABLE_NAME = 'PDV_T_GUIA' ;

-- ALTER TABLE `PDV_T_GUIA` ADD COLUMN `TIPO_CORRIDA` CHAR(50) NULL AFTER `HORA_CORRIDA`;