-- --------------------------------------------------------
-- Host:                         192.168.19.36
-- Versión del servidor:         5.1.45-community - MySQL Community Server (GPL)
-- SO del servidor:              Win32
-- HeidiSQL Versión:             10.1.0.5464
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para procedimiento CORPORATIVO.PDV_STORE_REGISTRA_BOLETO
DELIMITER //
CREATE DEFINER=`venta`@`%` PROCEDURE `PDV_STORE_REGISTRA_BOLETO`(
	IN `IN_TERMINAL` VARCHAR(5),
	IN `IN_TRABID` VARCHAR(7),
	IN `IN_ESTATUS` VARCHAR(1),
	IN `IN_ORIGEN` VARCHAR(5),
	IN `IN_DESTINO` VARCHAR(5),
	IN `IN_TARIFA` DOUBLE,
	IN `IN_FORMA_PAGO` INTEGER,
	IN `IN_TAQUILLA` INTEGER,
	IN `IN_TIPO_TARIFA` VARCHAR(1),
	IN `IN_CORRIDA` VARCHAR(10),
	IN `IN_FECHA` DATE,
	IN `IN_PASAJERO` VARCHAR(80),
	IN `IN_ASIENTO` INTEGER,
	IN `IN_OCUPANTE` INTEGER,
	IN `IN_FECHA_HORA` VARCHAR(20),
	IN `IN_RUTA` INTEGER,
	IN `IN_SERVICIO` VARCHAR(30),
	IN `IN_ID_PAGO_PINPAD_BANAMEX` VARCHAR(14),
	IN `IN_TC` VARCHAR(100),
	IN `IN_IVA` DOUBLE,
	IN `IN_PAGO_SUB` VARCHAR(5)








)
    COMMENT 'Ver. 2019-05-13'
BEGIN
    
DECLARE IDBOLETO  INT;
DECLARE EXISTE_ASIENTO INT DEFAULT 0;
DECLARE IDASIENTO INT DEFAULT 0;
DECLARE BOLETO_OK,ASIENTO_OK INT DEFAULT 0;
DECLARE snameTableTest   VARCHAR(512);
DECLARE sqlTable   VARCHAR(1024);
DECLARE OUT_SERVICIO INTEGER DEFAULT 0;
DECLARE TOTALIVA DOUBLE;
DECLARE IVA_COBRO  DOUBLE;

SELECT D.IMP_IVA INTO IVA_COBRO
    FROM PDV_C_TARIFA T INNER JOIN SERVICIOS S ON T.ID_SERVICIO = S.TIPOSERVICIO
                        INNER JOIN PDV_C_TARIFA_D D ON D.ID_TARIFA = T.ID_TARIFA
    WHERE T.ID_TRAMO = (SELECT T.ID_TRAMO FROM T_C_TRAMO T WHERE T.ORIGEN = IN_ORIGEN AND T.DESTINO = IN_DESTINO) AND S.TIPOSERVICIO = IN_SERVICIO AND FECHA_HORA_APLICA <= NOW()
    ORDER BY FECHA_HORA_APLICA DESC
    LIMIT 1;

IF IVA_COBRO = -100 THEN
 SET IVA_COBRO = 0;
END IF;

SELECT COALESCE(IN_TARIFA - (IN_TARIFA / ((IVA_COBRO / 100) + 1) ),0) AS IVATOTAL INTO TOTALIVA;

CALL PDV_STORE_BUSCA_BOLETO_V(IN_CORRIDA,IN_FECHA,IN_ASIENTO,BOLETO_OK);

IF BOLETO_OK = 0 THEN
   SELECT (COALESCE(MAX(ID_BOLETO),0) + 1)AS IDX INTO IDBOLETO
   FROM PDV_T_BOLETO
	WHERE TRAB_ID = IN_TRABID AND ID_TERMINAL = IN_TERMINAL;
		
	INSERT INTO PDV_T_BOLETO(ID_BOLETO, ID_TERMINAL, TRAB_ID, ESTATUS, ORIGEN, DESTINO, TARIFA, ID_FORMA_PAGO, ID_TAQUILLA, TIPO_TARIFA, FECHA_HORA_BOLETO, ID_CORRIDA, FECHA, NOMBRE_PASAJERO, NO_ASIENTO, ID_OCUPANTE, ID_RUTA, TIPOSERVICIO, ID_PAGO_PINPAD_BANAMEX, TC, IVA, TOTAL_IVA, ID_FORMA_PAGO_SUB)
	VALUES(IDBOLETO, IN_TERMINAL, IN_TRABID, IN_ESTATUS, IN_ORIGEN, IN_DESTINO, IN_TARIFA, IN_FORMA_PAGO, IN_TAQUILLA, IN_TIPO_TARIFA, NOW(), IN_CORRIDA, IN_FECHA, IN_PASAJERO, IN_ASIENTO, IN_OCUPANTE, IN_RUTA, IN_SERVICIO, IN_ID_PAGO_PINPAD_BANAMEX,IN_TC, IVA_COBRO, TOTALIVA, IN_PAGO_SUB);
		 
	DELETE FROM PDV_T_ASIENTO WHERE ID_CORRIDA = IN_CORRIDA AND CAST(FECHA_HORA_CORRIDA AS DATE) = IN_FECHA AND NO_ASIENTO = IN_ASIENTO AND TRAB_ID = IN_TRABID AND ORIGEN = IN_ORIGEN AND DESTINO = IN_DESTINO;

	INSERT INTO PDV_T_ASIENTO(ID_CORRIDA, FECHA_HORA_CORRIDA, NO_ASIENTO, NOMBRE_PASAJERO, TRAB_ID,ORIGEN,DESTINO,STATUS,FECHA_HORA_ORIGEN)
   VALUES(IN_CORRIDA,IN_FECHA_HORA, IN_ASIENTO, IN_PASAJERO, IN_TRABID, IN_ORIGEN, IN_DESTINO,'V', NOW());
	
	UPDATE PDV_T_ASIENTO SET STATUS = 'V' WHERE ID_CORRIDA = IN_CORRIDA AND CAST(FECHA_HORA_CORRIDA AS DATE) = IN_FECHA AND NO_ASIENTO = IN_ASIENTO AND TRAB_ID = IN_TRABID AND ORIGEN = IN_ORIGEN AND DESTINO = IN_DESTINO AND STATUS = 'O';
END IF;

END//
DELIMITER ;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
