INSERT INTO PDV_C_TERMINAL(ID_TERMINAL,IPV4,BD_USUARIO,BD_PASSWORD,ESTATUS,TIPO)
VALUES('MEX','192.168.2.152','venta','ventas','A','T');

INSERT INTO PDV_C_TERMINAL(ID_TERMINAL,IPV4,BD_USUARIO,BD_PASSWORD,ESTATUS,TIPO)
VALUES('JOJ','192.168.2.154','venta','ventas','A','T');

INSERT INTO PDV_C_TERMINAL(ID_TERMINAL,IPV4,BD_USUARIO,BD_PASSWORD,ESTATUS,TIPO)
VALUES('CCS','192.168.2.153','venta','ventas','A','T');

INSERT INTO PDV_C_TERMINAL(ID_TERMINAL,IPV4,BD_USUARIO,BD_PASSWORD,ESTATUS,TIPO)
VALUES('CUE','192.168.2.151','venta','ventas','A','T');

INSERT INTO PDV_C_TERMINAL(ID_TERMINAL,IPV4,BD_USUARIO,BD_PASSWORD,ESTATUS,TIPO)
VALUES('PTE','192.168.2.155','venta','ventas','A','T');

INSERT INTO PDV_C_TERMINAL(ID_TERMINAL,IPV4,BD_USUARIO,BD_PASSWORD,ESTATUS,TIPO)
VALUES('AER','192.168.2.156','venta','ventas','A','T');

INSERT INTO PDV_C_TERMINAL(ID_TERMINAL,IPV4,BD_USUARIO,BD_PASSWORD,ESTATUS,TIPO)
VALUES('ZAC','192.168.2.151','venta','ventas','A','T');

INSERT INTO PDV_C_TERMINAL(ID_TERMINAL,IPV4,BD_USUARIO,BD_PASSWORD,ESTATUS,TIPO)
VALUES('COR','192.168.1.13','venta','ventas','A','T');
