program PDV;

uses
  Forms,
  Windows,
  frm_pdv_main in '..\acceso\frm_pdv_main.pas' {Frm_main},
  Frm_Ini_Config in '..\acceso\Frm_Ini_Config.pas' {Frm_Ini},
  DMdb in '..\db\DMdb.pas' {DM: TDataModule},
  comun in '..\comun\comun.pas',
  Frm_splash in '..\acceso\Frm_splash.pas' {Frm_ini_splash},
  Frm_acc_grupos in '..\acceso\Frm_acc_grupos.pas' {Frm_grupos},
  Frm_grp_permiso in '..\acceso\Frm_grp_permiso.pas' {Frm_permisos_grps},
  Frm_acc_usuario in '..\acceso\Frm_acc_usuario.pas' {Frm_usuarios},
  u_main in '..\acceso\u_main.pas',
  frm_acc_password in '..\acceso\frm_acc_password.pas' {PasswordDlg},
  frm_bus_autobus in '..\buses\frm_bus_autobus.pas' {Frm_autobus},
  u_autobus in '..\buses\u_autobus.pas',
  Asiento in '..\buses\Asiento.pas',
  Frm_vta_main in '..\venta\Frm_vta_main.pas' {Frm_venta_principal},
  frm_cat_configuracion in '..\configuracion\frm_cat_configuracion.pas' {frm_cat_config},
  frm_iti_ocupante in '..\itinerario\frm_iti_ocupante.pas' {Frm_ocupante},
  U_venta in '..\venta\U_venta.pas',
  ThreadMainServer in '..\Threads\ThreadMainServer.pas',
  DrawAsiento in '..\buses\DrawAsiento.pas',
  Frm_vta_pagos in '..\venta\Frm_vta_pagos.pas' {frm_forma_pago},
  Frm_formas_pago in '..\venta\Frm_formas_pago.pas' {frm_pago_boleto},
  frm_usuario_boletos in '..\venta\frm_usuario_boletos.pas' {frm_nombre_boleto},
  frm_mensaje_corrida in '..\venta\frm_mensaje_corrida.pas' {Frm_Corrida_Ocupada},
  Frm_vta_reservacion in '..\venta\Frm_vta_reservacion.pas' {Frm_reservacion},
  frm_reservacion_vender in '..\venta\frm_reservacion_vender.pas' {frm_reservados_vta},
  Frm_cancela_boletos in '..\venta\Frm_cancela_boletos.pas' {Frm_cancelaciones},
  Frm_cancela_reservacion in '..\venta\Frm_cancela_reservacion.pas' {Frm_reserva_cancela},
  U_acceso in '..\acceso\U_acceso.pas',
  TRemotoTodos in '..\Threads\TRemotoTodos.pas',
  TRemotoRuta in '..\Threads\TRemotoRuta.pas',
  ThreadRemoto in '..\Threads\ThreadRemoto.pas',
  frm_guias_despacho in '..\guias\frm_guias_despacho.pas' {frm_guias_servicio},
  u_guias in '..\guias\u_guias.pas',
  CNumLtr in '..\comun\CNumLtr.pas',
  TRemotoPorTerminal in '..\Threads\TRemotoPorTerminal.pas',
  frm_vta_libera_corrida in '..\venta\frm_vta_libera_corrida.pas' {frm_corrida_libera},
  Frm_vta_agrupa_corrida in '..\venta\Frm_vta_agrupa_corrida.pas' {Frm_corrida_agrupa},
  corridas in '..\corridas\corridas.pas' {frmCorridas},
  extras in '..\extras\extras.pas' {frmExtras},
  U_itinerario in '..\itinerario\U_itinerario.pas',
  frm_iti_itinerario in '..\itinerario\frm_iti_itinerario.pas' {Frm_itinerario},
  frmMbusquedas in '..\Busquedas\frmMbusquedas.pas' {frmBusqueda},
  frmCrutas in '..\Rutas\frmCrutas.pas' {frmRutas},
  frmCtramos in '..\Tramos\frmCtramos.pas' {frmTramos},
  comunii in '..\comunII\comunii.pas',
  frmCorte in '..\Cortes\frmCorte.pas' {frmCortes},
  frmCorteTipoServicio in '..\Cortes\frmCorteTipoServicio.pas' {frmCorteServicio},
  frmFaltantesYSobrantes in '..\FaltantesSobrantes\frmFaltantesYSobrantes.pas' {frmFaltantesSobrantes},
  Frm_fondo_inicial in '..\venta\Frm_fondo_inicial.pas' {Frm_reg_fondo_inicial},
  frmMrecolecccion in '..\recoleccion\frmMrecolecccion.pas' {frmRecoleccion},
  Urecoleccion in '..\recoleccion\Urecoleccion.pas',
  frm_vta_status_corrida in '..\venta\frm_vta_status_corrida.pas' {frm_status_corrida},
  frm_acc_password_nuevo in '..\acceso\frm_acc_password_nuevo.pas' {frm_pass_nuevo},
  Frm_vta_reservacion1 in '..\venta\Frm_vta_reservacion1.pas' {frm_vta_reserva},
  frm_venta_anticipada in '..\venta\frm_venta_anticipada.pas' {frm_vta_anticipada},
  frm_periodo_vacacional in '..\acceso\frm_periodo_vacacional.pas' {frm_vacacional},
  frm_vta_anticipados in '..\venta\frm_vta_anticipados.pas' {Frm_venta_anticipados},
  frm_anticipada_venta in '..\venta\frm_anticipada_venta.pas' {frm_anticipa_vender},
  uCortes in '..\Cortes\uCortes.pas',
  frmAdministracionCortes in '..\Cortes\frmAdministracionCortes.pas' {frmAdministracionCorte},
  TLiberaAsientosRuta in '..\Threads\TLiberaAsientosRuta.pas',
  ThreadCorrida in '..\Threads\ThreadCorrida.pas',
  frm_cambio_password in '..\acceso\frm_cambio_password.pas' {Frm_contrasena},
  ThreadDetalleRuta in '..\Threads\ThreadDetalleRuta.pas',
  ThreadTrazaLugar in '..\Threads\ThreadTrazaLugar.pas',
  ThreadRutas in '..\Threads\ThreadRutas.pas',
  frm_password_cambio in '..\acceso\frm_password_cambio.pas' {frm_cambio},
  frmCorteFinDeDia in '..\Cortes\frmCorteFinDeDia.pas' {frmCorteFinDia},
  frmMenuTarifas in '..\Tarifas\frmMenuTarifas.pas' {frmMenuTarifa},
  frmATarifa in '..\Tarifas\frmATarifa.pas' {frmATarifas},
  frmCTarifas in '..\Tarifas\frmCTarifas.pas' {frmCTarifa},
  uTarifas in '..\Tarifas\uTarifas.pas',
  frm_reimpresion in '..\guias\frm_reimpresion.pas' {frm_reimprimeguia},
  frm_ultimaventa in '..\venta\frm_ultimaventa.pas' {frm_venta_ultima},
  frm_aparta_asientos in '..\venta\frm_aparta_asientos.pas' {frm_aparta_lugares},
  frm_nombre in '..\venta\frm_nombre.pas' {Frm_credencial},
  u_boleto in '..\venta\u_boleto.pas',
  u_venta_nueva in '..\venta\u_venta_nueva.pas' {frm_nueva_venta},
  u_comun_venta in '..\comun\u_comun_venta.pas',
  frm_pago_nueva in '..\venta\frm_pago_nueva.pas' {frm_nueva_pagoF},
  u_fondo_inicial_nuevo in '..\venta\u_fondo_inicial_nuevo.pas' {frm_fondo_nuevo},
  frm_historico_venta in '..\venta\frm_historico_venta.pas' {frm_historico},
  Unit1 in '..\Calculator1508051252002\Unit1.pas' {frm_calculadora},
  Unit2 in '..\Calculator1508051252002\Unit2.pas' {Form2},
  frm_calendario_venta in '..\venta\frm_calendario_venta.pas' {frm_calendario},
  u_ithaca_print in '..\venta\u_ithaca_print.pas',
  frm_personalizacion_boletos in '..\venta\frm_personalizacion_boletos.pas' {Frm_boleto_personalizado},
  frm_cancela_reservacion_new in '..\venta\frm_cancela_reservacion_new.pas' {frm_cancela_new},
  frm_cancela_boletos_new in '..\venta\frm_cancela_boletos_new.pas' {frm_cancelacion_boletos},
  frmUsuarios in '..\usuariosII\frmUsuarios.pas' {frmUsuario},
  Uusuarios in '..\usuariosII\Uusuarios.pas',
  frm_agencia in '..\agencia\frm_agencia.pas' {frm_agencias},
  frm_visualiza_corridas in '..\agencia\frm_visualiza_corridas.pas' {frm_agencia_corrida},
  frm_asignacion_agencia in '..\agencia\frm_asignacion_agencia.pas' {frm_relacion_terminal},
  frmCRutaII in '..\RutasII\frmCRutaII.pas' {frmCRutasII},
  frmCTerminales in '..\RutasII\frmCTerminales.pas' {frmTerminales},
  uRutasII in '..\RutasII\uRutasII.pas',
  Uterminales in '..\RutasII\Uterminales.pas',
  u_ToshibaMini_print in '..\venta\u_ToshibaMini_print.pas',
  frmImportaTarifa in '..\Tarifas\frmImportaTarifa.pas' {importaTarifas},
  frmModificacionTarifas in '..\Tarifas\frmModificacionTarifas.pas' {frmModificaTarifa},
  uImportarTarifas in '..\Tarifas\uImportarTarifas.pas',
  u_venta_usuarios in '..\larios\u_venta_usuarios.pas',
  u_cobro_banamex in '..\venta\u_cobro_banamex.pas',
  frm_pinpad_banamex_cancelar in '..\venta\frm_pinpad_banamex_cancelar.pas' {pinpad_banamex_cancelar},
  frmRutasRepetidas in '..\RutasII\frmRutasRepetidas.pas' {frmRutaRepetida},
  frm_src_taquillas in '..\taquilla\frm_src_taquillas.pas' {frm_taquilla},
  frm_elimina_usuario in '..\acceso\frm_elimina_usuario.pas' {frm_usuario_baja},
  frm_registro_folios in '..\venta\frm_registro_folios.pas' {frm_folio_registro},
  frmPrecorte in '..\Cortes\frmPrecorte.pas' {frm_precorte},
  u_comun_base in 'u_comun_base.pas',
  u_impresion in '..\comun\u_impresion.pas',
  ThreadPingServer in '..\Threads\ThreadPingServer.pas',
  u_validaTarjeta in '..\comun\u_validaTarjeta.pas',
  frm_tarjeta_catalogo in '..\venta\frm_tarjeta_catalogo.pas' {frm_catalogo_pago},
  frmModificacionRemotaGuias in '..\ModificacionRemotaGuias\frmModificacionRemotaGuias.pas' {ModificacionRemotaGuias},
  u_gral_venta in '..\venta\u_gral_venta.pas',
  frm_lectorBarras in 'frm_lectorBarras.pas' {frm_lector},
  Hashes in '..\comun\Hashes.pas',
  u_ping in '..\extras\u_ping.pas',
  frm_codigoBars in '..\corridas\frm_codigoBars.pas' {frm_bars},
  u_barsCode in '..\corridas\u_barsCode.pas',
  uModificacionRemotaGuias in '..\ModificacionRemotaGuias\uModificacionRemotaGuias.pas',
  frmAsignacionFondo in '..\Cortes\frmAsignacionFondo.pas' {frmAsignarFondo},
  frmReportePrivilegios in '..\reportePrivilegios\frmReportePrivilegios.pas' {frmReportePrivilegio},
  uReportePrivilegios in '..\reportePrivilegios\uReportePrivilegios.pas',
  frm_imprime_abierto in '..\venta\frm_imprime_abierto.pas' {frm_print_abierto},
  u_vigencia_abierto in '..\venta\u_vigencia_abierto.pas' {frm_vigencia_abierto},
  frmImportesAlertas in '..\importesAlertas\frmImportesAlertas.pas' {frmImportes},
  funciones in '..\importesAlertas\funciones.pas',
  CPort in '..\venta\CPort.pas',
  CPortSetup in '..\venta\CPortSetup.pas',
  CPortCtl in '..\venta\CPortCtl.pas',
  CPortEsc in '..\venta\CPortEsc.pas',
  CPortTrmSet in '..\venta\CPortTrmSet.pas' {ComTrmSetForm},
  e_reporte in '..\venta\e_reporte.pas' {Frm_reporte},
  u_pax_corrida in '..\venta\u_pax_corrida.pas' {frm_pax_fik},
  modificarCorrida in '..\corridas\modificarCorrida.pas' {frmModificarCorrida},
  updateCorridasRemotas in '..\corridas\updateCorridasRemotas.pas' {frm_updateCorridas},
  uQuerysNuevos in '..\comun\uQuerysNuevos.pas',
  u_especial in '..\venta\u_especial.pas',
  uLitteScreen in '..\pantalla\uLitteScreen.pas';

{$R *.res}

begin
 //Attempt to create a named mutex
  CreateMutex(nil, false, 'MyApp1');
{  if GetLastError = ERROR_ALREADY_EXISTS then begin
    SendMessage(HWND_BROADCAST,RegisterWindowMessage('MyApp1'),0,0);
   //Lets quit
    Halt(0);
  end;}

{  with TFormSplash.Create(Application) do
    Execute;}
  Application.CreateForm(TDM, DM);
  Application.Initialize;
  with TFrm_ini_splash.Create(Application) do
      Execute;
  Application.CreateForm(Tfrm_main, Frm_main);
  Application.CreateForm(Tpinpad_banamex_cancelar, pinpad_banamex_cancelar);
  Application.CreateForm(TfrmRutaRepetida, frmRutaRepetida);
  Application.CreateForm(Tfrm_catalogo_pago, frm_catalogo_pago);////
  Application.Run;
end.
